#204,
rivm-syso/Analyse-Together pull request #210
Opened 2023-04-21 09:46 UTC by elma13

script to get the data from meta table and create plots to analyse download duration

2023-04-25 16:00 UTC, jspijker requested changes
This doesn't work. The script won't load any libraries nor is any pool object present. See for example the first 20 or so lines from  create_data_request script.

2023-05-01 07:12 UTC, elma13 commented
Thanks for checking, I added the libraries, can you check it again if this is working?

2023-05-01 10:29 UTC, jspijker approved these changes

2023-05-01 10:30 UTC, jspijker commented
Now it works fine

2023-05-01 11:08 UTC, merged