Issue 391
rivm-syso/Analyse-Together pull request #398
Opened 2024-10-31 14:11 UTC by elma13

For the choose tab, the data availability is checked in the measurements table, and directly shown in a calender plot. #391 
And some fix if there is no data in database, that the app still runs #396

2024-10-31 14:15 UTC, elma13 commented
@jspijker this is major adjustment in how to give information about availability to the user. In #397  I will continue adding the map too to the choose tab, and that the data is only gathered once from the cache. So that is the next step.

2024-11-04 15:06 UTC, jspijker requested changes
Works, but I get English messages instead of Dutch. Should we fix this before next release or later?

2024-11-04 15:06 UTC, jspijker commented on modules/show_data_avail_cache.R
> +        })
Translation?

2024-11-08 09:45 UTC, elma13 commented
@jspijker, I updated the translation for (I hope) all the modules. And added the info to the manual of function get_location_coordinates

2024-11-11 09:40 UTC, jspijker approved these changes
data availability works, Still some minor issues with i18n.

2024-11-11 10:10 UTC, merged